<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.willwinder</groupId>
        <artifactId>ugs-platform-parent</artifactId>
        <version>${revision}${changelist}</version>
    </parent>

    <artifactId>ugs-platform-surfacescanner</artifactId>
    <packaging>nbm</packaging>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.netbeans.utilities</groupId>
            <artifactId>nbm-maven-plugin</artifactId>
            <version>4.8</version>
            <extensions>true</extensions>
            <configuration>
                <moduleDependencies>
					<module>
					  <id>com.willwinder:serialcontrol</id>
					</module>
                    <module>
                        <id>org.netbeans.api:org-netbeans-api-annotations-common</id>
                        <explicitValue>org.netbeans.api.annotations.common/1</explicitValue>
                    </module>
                    <module>
                        <id>org.openide:org-openide-awt</id>
                        <explicitValue>org.openide.awt/1</explicitValue>
                    </module>
                    <module>
                        <id>org.openide:org-openide-dialogs</id>
                        <explicitValue>org.openide.dialogs/1</explicitValue>
                    </module>
                    <module>
                        <id>org.openide:org-openide-util</id>
                        <explicitValue>org.openide.util/9</explicitValue>
                    </module>
                    <module>
                        <id>org.openide:org-openide-util-lookup</id>
                        <explicitValue>org.openide.util.lookup/1</explicitValue>
                    </module>
                    <module>
                        <id>org.openide:org-openide-windows</id>
                        <explicitValue>org.openide.windows/2</explicitValue>
                    </module>
                </moduleDependencies>
                <publicPackages>
                </publicPackages>
            </configuration>
        </plugin>
    </plugins>
</build>


    <dependencies>
	<dependency>
		<groupId>org.netbeans.api</groupId>
		  <artifactId>org-openide-io</artifactId>
		  <version>RELEASE230</version>
		</dependency>
		<dependency>
			<groupId>com.willwinder</groupId>
			<artifactId>ugs-platform-plugin-serialControl</artifactId>
			<version>${project.version}</version>
		</dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-dialogs</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fazecast</groupId>
            <artifactId>jSerialComm</artifactId>
            <version>2.11.0</version> <!-- or latest stable version -->
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${gson.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-api-annotations-common</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-awt</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-windows</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util-lookup</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>ugs-platform-visualizer</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>ugs-platform-ugslib</artifactId>
            <version>${project.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.willwinder</groupId>
            <artifactId>ugs-platform-ugscore</artifactId>
            <version>${project.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util-ui</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-options-api</artifactId>
            <version>${netbeans.version}</version>
        </dependency>

        <dependency>
            <groupId>org.netbeans.modules</groupId>
            <artifactId>org-openide-util-ui-svg</artifactId>
            <version>${netbeans.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
